# Site settings
title: ANDRES-ALEJANDRO
email: ""
website: "/"
description: "Invitación para el cumpleaños número DOS de Andres y Alejandro (Danielita también)"
url: "https://andres-alejandro.github.io"
baseurl: "/"
facebook_username: ""
twitter_username: ""
instagram_username: ""
github_username:  ""
deviantart_username: ""
flickr_username: ""
discus_shortname: ""
share: true

# Owner/author information
owner:
  name:   andres-alejandro
  avatar: avatar.png
  favicon: favicon.ico
  info: Andres y Alejandro

# Settings for comments helper
# Set 'provider' to the comment provider you want to use. (i.e.  Disqus, Intense Debate, livefyre, or Facebook Comments)
# Set 'provider' to false to turn commenting off globally.
#Set 'provider: false' to disable comments globally.
# Disable comments for individual pages/posts by specifying 'comments: false' in the page/post YAML Front Matter.
#
comments :
  provider : disqus
  disqus :
    short_name : ""

# Internal nav
nav:
  - Inicio: "https://andres-alejandro.github.io/"
  - ¿Dónde?: "https://andres-alejandro.github.io/lugar/"
  - Fotos: "https://andres-alejandro.github.io/gallery/"
  #- NOSOTROS: "https://andres-alejandro.github.io/about/"

# All translation keys
translations:
 # 404.html
  permalink: "/404.html"

# Server
destination:      	 ./_site
port:             	 4000


# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
paginate_path: "/page:num/"
permalink: "/:title/"
categories_path: "/category/"
tags_path: "/tag/"
gems: 
 - jekyll-paginate
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# SiteMap
sitemap:
    file: "/sitemap.xml"
    exclude:
        - "/atom.xml"
        - "/feed.xml"
        - "/feed/index.xml"
    include_posts:
        - "/writing/"
    change_frequency_name: "change_frequency"
    priority_name: "priority"
